# This file should be copied to /home/yuvalif/lancedb/c/Cargo.toml

[package]
name = "lancedb-c"
version = "0.33.0"
edition = "2021"
description = "C bindings for LanceDB"
license = "Apache-2.0"
repository = "https://github.com/yuvalif/lancedb-c"
keywords = ["database", "vector", "search", "c", "ffi"]
categories = ["database", "api-bindings"]
rust-version = "1.91.0"

[lib]
name = "lancedb"
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
tokio = { version = "1.23", features = ["rt-multi-thread"] }
libc = "0.2"
lancedb = { version = "0.33.0", features = ["remote"] }
lance = "=9.0.0"
lance-io = "=9.0.0"
lance-namespace = "=9.0.0"
arrow-array = "58.0"
arrow-data = "58.0"
arrow-schema = "58.0"
datafusion-common = "54"
datafusion-expr = "54"
datafusion-functions-json = "0.54"
datafusion-functions = { version = "54", default-features = false, features = ["string_expressions"] }
datafusion-functions-nested = "54"
datafusion-physical-expr = "54"
futures = "0"
stacker = "0.1"
chrono = "0"

# This is done to build my local version of lance for cache injection.
[patch.crates-io]
lance = { path = "../lance/rust/lance" }
lance-arrow = { path = "../lance/rust/lance-arrow" }
lance-arrow-scalar = { path = "../lance/rust/arrow-scalar" }
lance-arrow-stats = { path = "../lance/rust/arrow-stats" }
lance-bitpacking = { path = "../lance/rust/compression/bitpacking" }
lance-core = { path = "../lance/rust/lance-core" }
lance-datafusion = { path = "../lance/rust/lance-datafusion" }
lance-datagen = { path = "../lance/rust/lance-datagen" }
lance-derive = { path = "../lance/rust/lance-derive" }
lance-encoding = { path = "../lance/rust/lance-encoding" }
lance-file = { path = "../lance/rust/lance-file" }
lance-geo = { path = "../lance/rust/lance-geo" }
lance-index = { path = "../lance/rust/lance-index" }
lance-index-core = { path = "../lance/rust/lance-index-core" }
lance-io = { path = "../lance/rust/lance-io" }
lance-linalg = { path = "../lance/rust/lance-linalg" }
lance-namespace = { path = "../lance/rust/lance-namespace" }
lance-namespace-datafusion = { path = "../lance/rust/lance-namespace-datafusion" }
lance-namespace-impls = { path = "../lance/rust/lance-namespace-impls" }
lance-select = { path = "../lance/rust/lance-select" }
lance-table = { path = "../lance/rust/lance-table" }
lance-tokenizer = { path = "../lance/rust/lance-tokenizer" }
fsst = { path = "../lance/rust/compression/fsst" }
